CREATE TABLE IF NOT EXISTS user (id text PRIMARY KEY NOT NULL, name text NOT NULL, email text NOT NULL, email_verified integer NOT NULL DEFAULT false, image text, first_name text, last_name text, role text NOT NULL DEFAULT 'client', created_at integer NOT NULL, updated_at integer NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS user_email_unique ON user (email);
CREATE TABLE IF NOT EXISTS session (id text PRIMARY KEY NOT NULL, expires_at integer NOT NULL, token text NOT NULL, created_at integer NOT NULL, updated_at integer NOT NULL, ip_address text, user_agent text, user_id text NOT NULL REFERENCES user(id) ON DELETE CASCADE);
CREATE UNIQUE INDEX IF NOT EXISTS session_token_unique ON session (token);
CREATE INDEX IF NOT EXISTS session_user_idx ON session (user_id);
CREATE TABLE IF NOT EXISTS account (id text PRIMARY KEY NOT NULL, account_id text NOT NULL, provider_id text NOT NULL, user_id text NOT NULL REFERENCES user(id) ON DELETE CASCADE, access_token text, refresh_token text, id_token text, access_token_expires_at integer, refresh_token_expires_at integer, scope text, password text, created_at integer NOT NULL, updated_at integer NOT NULL);
CREATE TABLE IF NOT EXISTS verification (id text PRIMARY KEY NOT NULL, identifier text NOT NULL, value text NOT NULL, expires_at integer NOT NULL, created_at integer, updated_at integer);
CREATE TABLE IF NOT EXISTS appointment (id text PRIMARY KEY NOT NULL, client_id text NOT NULL REFERENCES user(id) ON DELETE CASCADE, service text NOT NULL, starts_at integer NOT NULL, status text NOT NULL DEFAULT 'pending', notes text, therapist text NOT NULL, therapy_mode text NOT NULL DEFAULT 'individual', created_at integer NOT NULL, updated_at integer NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS appointment_therapist_start_unique ON appointment (therapist, starts_at);
CREATE INDEX IF NOT EXISTS appointment_client_start_idx ON appointment (client_id, starts_at);
CREATE INDEX IF NOT EXISTS appointment_status_start_idx ON appointment (status, starts_at);
