import type { Role } from "@/lib/roles";
import type { Locale } from "@/lib/site-content";

export const protectedCopy = {
  en: {
    navigation: {
      label: "Account navigation",
      dashboard: "Dashboard",
      appointments: "Appointments",
      book: "Book",
      availability: "Availability",
      staff: "Staff",
      profile: "Profile",
      logout: "Log out",
      accountType: "Account type",
    },
    roles: { USER: "Client", THERAPIST: "Therapist", ADMIN: "Administrator" },
    common: {
      accessDenied: "You do not have access to that page. You are back in your workspace.",
      pending: "Working…",
      confirm: "Confirm",
      back: "Back",
    },
    clientDashboard: {
      eyebrow: "My account",
      welcome: (name: string) => `Welcome, ${name}`,
      book: "Book a session",
      appointments: "Appointments",
      privacy: "Data minimisation",
      privacyBody: "We only keep scheduling information necessary for this service.",
      profile: "Profile",
      recent: "Recent appointments",
      appointment: "Appointment",
      empty: "You do not have appointments yet.",
      viewAll: "View all appointments",
    },
    staffDashboard: {
      adminTitle: "Administration",
      therapistTitle: "Therapist workspace",
      addAvailability: "Add availability",
      appointments: "Appointments",
      upcoming: "Upcoming",
      actions: "Actions",
      viewAppointments: "View appointments",
      manageStaff: "Manage staff",
    },
    appointments: {
      clientTitle: "My appointments",
      staffTitle: "Appointments",
      appointment: "Appointment",
      emptyClient: "You do not have appointments yet.",
      emptyStaff: "There are no assigned appointments yet.",
      deletedUser: "Deleted user",
      client: "Client",
      therapist: "Therapist",
      confirm: "Confirm",
      complete: "Complete",
      cancel: "Cancel",
      confirmCancel: "Cancel this appointment? This action updates the client’s schedule.",
      confirmCancelAction: "Cancel appointment",
      statusError: "The appointment status could not be changed.",
      ownCancel: "Cancel appointment",
      confirmOwnCancel: "Cancel this appointment and release its future time?",
      ownCancelError: "The appointment could not be cancelled.",
      ends: "Ends",
      privacyNote: "This record contains no notes or health information.",
      reschedule: "Reschedule",
      deleteTitle: "Delete appointment",
      deleteActive:
        "The appointment will be cancelled and hidden from your account. Its future time will become available again.",
      deletePast: "The appointment will be hidden from your account.",
      deleteConfirmation: "I confirm that I want to delete this appointment.",
      deleteAction: "Delete appointment",
      deleteError: "The appointment could not be deleted.",
    },
    availability: {
      title: "Add availability",
      therapist: "Therapist",
      selectTherapist: "Select therapist",
      starts: "Starts at",
      ends: "Ends at",
      notice:
        "Create availability times only. This form does not collect client or health information.",
      publish: "Publish available time",
      publishError: "Availability could not be published.",
      adminOpen: "Open availability",
      therapistOpen: "My open availability",
      emptyAdmin: "There are no open availability times.",
      emptyTherapist: "You do not have any open availability times.",
      block: "Block",
      confirmBlock: "Block this availability time so clients can no longer book it?",
      confirmBlockAction: "Block time",
      blockError: "The availability could not be blocked.",
    },
    staff: {
      title: "Staff management",
      intro:
        "Only users with a verified email and enrolled TOTP can become therapists or administrators.",
      empty: "There are no other accounts to manage.",
      emailVerified: "Email verified",
      emailNotVerified: "Email not verified",
      totpEnabled: "TOTP enabled",
      totpNotEnabled: "TOTP not enrolled",
      eligible: "Eligible for a staff role",
      ineligible: "Verify the email address and enable TOTP before assigning a staff role.",
      makeTherapist: "Make therapist",
      makeAdmin: "Make administrator",
      removeRole: "Remove staff role",
      confirmRole: (name: string, role: string) => `Change ${name}’s role to ${role}?`,
      confirmRoleAction: "Confirm role change",
      roleError: "The staff role could not be changed.",
    },
    profile: {
      deleteTitle: "Delete account",
      deleteBody:
        "Access is revoked immediately and identifying account data is removed. De-identified records may remain only for the approved legal retention period.",
      currentPassword: "Current password",
      acknowledgement: "Type DELETE to confirm",
      deleteAction: "Permanently delete account",
      deleteError: "The deletion confirmation is invalid.",
      exportTitle: "Download your data",
      exportBody:
        "Download a readable PDF summary of your account data and associated appointments.",
      exportAction: "Download PDF",
    },
  },
  ro: {
    navigation: {
      label: "Navigație cont",
      dashboard: "Panou",
      appointments: "Programări",
      book: "Rezervă",
      availability: "Disponibilitate",
      staff: "Personal",
      profile: "Profil",
      logout: "Deconectare",
      accountType: "Tipul contului",
    },
    roles: { USER: "Client", THERAPIST: "Terapeut", ADMIN: "Administrator" },
    common: {
      accessDenied: "Nu ai acces la pagina respectivă. Ai revenit în spațiul contului tău.",
      pending: "Se procesează…",
      confirm: "Confirmă",
      back: "Înapoi",
    },
    clientDashboard: {
      eyebrow: "Contul meu",
      welcome: (name: string) => `Bine ai venit, ${name}`,
      book: "Rezervă o întâlnire",
      appointments: "Programări",
      privacy: "Reducerea la minimum a datelor",
      privacyBody: "Păstrăm doar informațiile de programare necesare acestui serviciu.",
      profile: "Profil",
      recent: "Programări recente",
      appointment: "Programare",
      empty: "Nu ai programări încă.",
      viewAll: "Vezi toate programările",
    },
    staffDashboard: {
      adminTitle: "Administrare",
      therapistTitle: "Spațiul terapeutului",
      addAvailability: "Adaugă disponibilitate",
      appointments: "Programări",
      upcoming: "Viitoare",
      actions: "Acțiuni",
      viewAppointments: "Vezi programările",
      manageStaff: "Administrează personalul",
    },
    appointments: {
      clientTitle: "Programările mele",
      staffTitle: "Programări",
      appointment: "Programare",
      emptyClient: "Nu ai programări încă.",
      emptyStaff: "Nu există programări alocate momentan.",
      deletedUser: "Utilizator șters",
      client: "Client",
      therapist: "Terapeut",
      confirm: "Confirmă",
      complete: "Finalizează",
      cancel: "Anulează",
      confirmCancel: "Anulezi această programare? Acțiunea actualizează programul clientului.",
      confirmCancelAction: "Anulează programarea",
      statusError: "Starea programării nu a putut fi schimbată.",
      ownCancel: "Anulează programarea",
      confirmOwnCancel: "Anulezi această programare și eliberezi intervalul viitor?",
      ownCancelError: "Programarea nu a putut fi anulată.",
      ends: "Se termină",
      privacyNote: "Această înregistrare nu conține note sau date despre sănătate.",
      reschedule: "Reprogramează",
      deleteTitle: "Șterge programarea",
      deleteActive:
        "Programarea va fi anulată și ascunsă din contul tău. Intervalul viitor va redeveni disponibil.",
      deletePast: "Programarea va fi ascunsă din contul tău.",
      deleteConfirmation: "Confirm că vreau să șterg această programare.",
      deleteAction: "Șterge programarea",
      deleteError: "Programarea nu a putut fi ștearsă.",
    },
    availability: {
      title: "Adaugă disponibilitate",
      therapist: "Terapeut",
      selectTherapist: "Selectează terapeutul",
      starts: "Începe la",
      ends: "Se termină la",
      notice:
        "Creează doar intervale de disponibilitate. Formularul nu colectează date despre client sau sănătate.",
      publish: "Publică intervalul",
      publishError: "Disponibilitatea nu a putut fi publicată.",
      adminOpen: "Disponibilitate deschisă",
      therapistOpen: "Disponibilitatea mea",
      emptyAdmin: "Nu există intervale de disponibilitate deschise.",
      emptyTherapist: "Nu ai intervale de disponibilitate deschise.",
      block: "Blochează",
      confirmBlock: "Blochezi acest interval astfel încât clienții să nu îl mai poată rezerva?",
      confirmBlockAction: "Blochează intervalul",
      blockError: "Intervalul nu a putut fi blocat.",
    },
    staff: {
      title: "Administrarea personalului",
      intro:
        "Doar utilizatorii cu email verificat și TOTP activ pot deveni terapeuți sau administratori.",
      empty: "Nu există alte conturi de administrat.",
      emailVerified: "Email verificat",
      emailNotVerified: "Email neverificat",
      totpEnabled: "TOTP activ",
      totpNotEnabled: "TOTP inactiv",
      eligible: "Eligibil pentru un rol de personal",
      ineligible: "Verifică adresa de email și activează TOTP înainte de atribuirea unui rol.",
      makeTherapist: "Devine terapeut",
      makeAdmin: "Devine administrator",
      removeRole: "Elimină rolul de personal",
      confirmRole: (name: string, role: string) => `Schimbi rolul lui ${name} în ${role}?`,
      confirmRoleAction: "Confirmă schimbarea rolului",
      roleError: "Rolul nu a putut fi schimbat.",
    },
    profile: {
      deleteTitle: "Ștergerea contului",
      deleteBody:
        "Accesul este revocat imediat, iar datele de identificare sunt eliminate. Datele anonimizate pot rămâne doar pentru perioada legală aprobată.",
      currentPassword: "Parola curentă",
      acknowledgement: "Scrie DELETE pentru confirmare",
      deleteAction: "Șterge definitiv contul",
      deleteError: "Confirmarea ștergerii nu este validă.",
      exportTitle: "Descarcă datele tale",
      exportBody:
        "Descarcă un rezumat PDF ușor de citit al datelor de cont și al programărilor asociate contului tău.",
      exportAction: "Descarcă PDF",
    },
  },
} as const;

export function getProtectedCopy(locale: Locale) {
  return protectedCopy[locale];
}

export function roleLabel(locale: Locale, role: Role) {
  return protectedCopy[locale].roles[role];
}
